// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXFxMcmaqqgYEzSvRS3ZFTmPTqen3C9HU',
    appId: '1:737203410075:web:6351ca1a7251e7e136623e',
    messagingSenderId: '737203410075',
    projectId: 'coursechat-462e3',
    authDomain: 'coursechat-462e3.firebaseapp.com',
    storageBucket: 'coursechat-462e3.appspot.com',
    measurementId: 'G-R31R5RQ4CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAEFnEB5O8vaopbkQvnbB77DocYA9jeWg',
    appId: '1:737203410075:android:33853154fa8667f236623e',
    messagingSenderId: '737203410075',
    projectId: 'coursechat-462e3',
    storageBucket: 'coursechat-462e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX9hQdGka1-QQhGonoLRU_DcahUjd1Xdw',
    appId: '1:737203410075:ios:902cede40569277136623e',
    messagingSenderId: '737203410075',
    projectId: 'coursechat-462e3',
    storageBucket: 'coursechat-462e3.appspot.com',
    iosBundleId: 'com.example.chatCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX9hQdGka1-QQhGonoLRU_DcahUjd1Xdw',
    appId: '1:737203410075:ios:902cede40569277136623e',
    messagingSenderId: '737203410075',
    projectId: 'coursechat-462e3',
    storageBucket: 'coursechat-462e3.appspot.com',
    iosBundleId: 'com.example.chatCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXFxMcmaqqgYEzSvRS3ZFTmPTqen3C9HU',
    appId: '1:737203410075:web:15dd36497defcc0836623e',
    messagingSenderId: '737203410075',
    projectId: 'coursechat-462e3',
    authDomain: 'coursechat-462e3.firebaseapp.com',
    storageBucket: 'coursechat-462e3.appspot.com',
    measurementId: 'G-W5WCCZNTQ3',
  );
}
